export const caseStudies = [
    {
        id: "nexus",
        slug: "nexus",
        title: "NEXUS ANALYTICS",
        industry: "SaaS",
        service: "AI Integration",
        metric: "+147%",
        metricLabel: "Revenue Growth",
        metricPos: "top-6 right-6",
        quote: "2Guys Digital transformed our complex data into a seamless user experience. The AI-driven predictive models they implemented have completely shifted how our enterprise clients interact with their data.",
        author: "John D. Moore",
        role: "CTO, Nexus SaaS",
        initials: "JD",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBdEJskWovU84Xq0CrLF77kQdM7kMFZ0tE9uxN10CMofwdUIEY8yDJDwWpsl0yV9ysJxmpte2Pmak6Pt6kzl93LruELTtHG8wgS76SamIHhwpadr-g-hVUxADCknYokFOsVvIEhqSSg6nxwtXQv8X8lC4VilFysqCuPR_KwUPHYQosMZ0ZqX-_TycCGzxsqPXRgkiKyg-n7l5mfzKny7y_efTAGzkM9PdcFIo7ENROOPRBcB310wAsnOQdETPhoHgPZBhzr-W3hpEc",
        reverse: false,
        fullDescription: "Nexus Analytics is a leading enterprise data platform. We were tasked with redesigning their core analytics dashboard and integrating a predictive modeling layer. The result was a 147% increase in revenue attributed to better data utilization by their end users.",
        link: "https://nexusanalytics.example.com",
    },
    {
        id: "vault",
        slug: "vault",
        title: "VAULT MOBILE",
        industry: "Fintech",
        service: "Development",
        metric: "+120%",
        metricLabel: "User Retention",
        metricPos: "top-6 left-6",
        quote: "A high-stakes project delivered with surgical precision. The security features and intuitive flow helped us secure our Series B funding within months of launch.",
        author: "Sarah Chen",
        role: "Founder, Vault Finance",
        initials: "SC",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDFu3RoG3pr3bl8IZfBZWqCdD5vxJTIo6UgIE4GKlkmu9fkrcSciWrErbUhcajvWkSGm0hvpONf-Uht4LItYwoJTz4sJAJiZji0Xk6T4G-WpCSsUzrWqYXW2Ld4gtIfQ4SfeQs-mZltoQPNrA9l4rhWn0lytzHmIXb7JG64sbIUE80CBJwaqKMsuAwnvv6Y74ioBXMkVI7gZkahg0IzC9FnrwfNiKVGZg2jW0E7MfpghBjzc9Zpd2L-qJxMwFnbFw92mUagnsaDwcg",
        reverse: true,
        fullDescription: "Vault Mobile is a high-security fintech application. We developed the entire mobile platform from scratch, focusing on zero-trust architecture and a frictionless onboarding experience. This clarity in user journey directly contributed to their successful Series B funding round.",
        link: "https://vaultmobile.example.com",
    },
];
